# This is a basic workflow to help you get started with Actions

name: Build CasaOS

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  
env:
  REPO_URL: https://github.com/IceWhaleTech/CasaOS.git
  REPO_BRANCH: main
  PACK_SH: pack.sh
  TZ: Asia/Shanghai

jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.17.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          
      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone $REPO_URL -b $REPO_BRANCH --recursive casa
          ln -sf /workdir/casa $GITHUB_WORKSPACE/casa
          ls
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Build frontend with nodejs and yarn
        run: |
          cd casa/UI
          ls
          yarn install
          yarn build
          
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          working_dir: /workdir/casa
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: casa
          targets: linux/amd64,linux/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          
      - name: List Files
        run: |
          ls
          cd casa/build
          ls
          echo "::set-output name=status::success"
          
      - name: Pack builds
        run: |
          chmod +x $PACK_SH
          $GITHUB_WORKSPACE/$PACK_SH
          
      - name: Publish Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: /workdir/casa/upload/
          tag: v1.30
          name: ceshi
          allow_override: true
